R/app_json.R

See https://github.com/posit-dev/shinylive/pull/64 for details.

Set wasm engine when templating for Shinylive

---

R/assets.R

Consider the use of `assets_install_link()` with a relative path:
```
> shinylive::assets_install_link('../shinylive')
```
The created symbolic link is then relative,
```
$ ls -l /Users/georgestagg/Library/Caches/shinylive/
total 0
lrwxr-xr-x  1 georgestagg  staff  18 13 Sep 10:05 shinylive-0.2.0 -> ../shinylive/build
```
But I would expect it to create a symbolic link with an absolute path, formed relative to the working directory at the time of running `assets_install_link()`.
This PR does that.

Ensure asset directory symlink is an absolute path

---

R/assets.R

My quarto presentations error with a `utils::download.file` timeout (defaults to 60s, expecting ~4MB/s for the 250MB `shinylive` archive). Not sure if it's limited by my internet or the github release artifacts server throttling downloads, but regardless this exceeds the guidelines in `?utils::download.file`:
> It is unrealistic to require download times of less than 1s/MB.
Just temporarily bumping the download timeout to accommodate the file size. Not sure how much you want to engineer this, but this could even catch the error and check to see if it failed due to a timeout, and if so suggest rerunning with `R_DEFAULT_INTERNET_TIMEOUT` increased.

Increasing download timeout

---

DESCRIPTION
NEWS.md
R/assets.R

feat: Use `{httr2}` to download assets to avoid timeout and give a progress bar

---

DESCRIPTION
NEWS.md
R/export.R
README.md
man/export.Rd

feat: Use `httpuv::runStaticServer(dir)` instead of `{plumber}`

---

DESCRIPTION
R/export.R
R/packages.R
R/quarto_ext.R
R/version.R
man/export.Rd
man/quarto_ext.Rd
tests/testthat/test-quarto_ext.R

Fixes #65 
----------
A first-pass implementation of #63.
Exports shinylive apps with Wasm R binary packages downloaded and included in `.../shinylive/webr/packages`. Metadata is stored in `.../shinylive/webr/packages/metadata.rds` and loaded at runtime.
For `shinylive::export()`, you can disable Wasm package bundling with `wasm_packages = FALSE`. And disable using the cache with `package_cache = FALSE`. Both are `TRUE` by default, meaning Wasm packages will be downloaded and bundled.
For Quarto documents with embedded R Shinylive apps, `quarto_ext.R` is updated so that `app.json` bundles passed to the `shinylive` R package are decoded onto disk, and then R Wasm binaries are downloaded using the same tools as created for `shinylive::export()`. Finally the resulting list of binaries are …

Export R shinylive apps with Wasm package binaries included in static assets

---

DESCRIPTION
R/quarto_ext.R
tests/testthat/test-quarto_ext.R

Base64 decoding of files in `app.json` is currently broken by the changes in #72. This PR switches to `jsonlite`'s implementation (removing a dependency), and fixes the problem.
Also, use `try()` in the case of binary files so as to recover from a base64 decode error, since binary files likely don't affect the result of renv package dependency resolution in any case.

Switch from base64enc to jsonlite

---

NEWS.md
R/assets.R
R/deps.R
R/export.R
R/quarto_ext.R
man/assets.Rd
man/export.Rd

Adds a new `assets_version` argument to `export()` that then propagates throughout the export process. This makes it possible to use `shinylive::export()` with asset versions other than the one currently used by default in the package.
The primary use case was to allow me to use the 0.4.1 assets even though the package is currently tied to 0.3.0. I used this to be able to use the preview version of shinylive with the wasm package library before it was officially tied to the package.
With this change `assets_version()` reports the current default version used by the package. Users may either set `assets_version` when calling `export()` or they may use the `SHINYLIVE_ASSETS_VERSION` envvar to achieve the same thing. The envvar is necessary for CI environments where it's easy to set this …

feat: Choose asset version at export

---

R/packages.R

Adds an envvar `SHINYLIVE_DOWNLOAD_WASM_CORE_PACKAGES` geared toward advanced users who want to use the development versions of packages that are included in the core set of packages used with shinylive.
The goal is that `SHINYLIVE_DOWNLOAD_WASM_CORE_PACKAGES` could take a list of packages that would normally **not** be download with the wasm package bundle because they appear in the core package list and mark them as "downloadable".
In particular, I needed this to be able to include the in-development version of bslib in workshop materials.
Some packages are patched in the `r-wasm` org and probably shouldn't be downloadable, but I'm also assuming that someone using this envvar will have that context. (In other words, this is an advanced usage feature.)

feat: envvar to allow downloading core packges in wasm package library

---

tests/testthat/apps/app-r/app.R
tests/testthat/apps/server-r/global.R
tests/testthat/apps/server-r/server.R
tests/testthat/apps/server-r/ui.R
tests/testthat/test-export.R

Makes it easier to use the test fixtures for interactive testing and development

tests(export): Refactor export tests to use test files

---

.github/workflows/R-CMD-check.yaml
tests/testthat/test-quarto_ext.R

Three big changes:
1. We now run the R package tests using the shinylive assets we built and installed in the previous steps (before we were building shinylive but testing with the default assets version).
2. We now test r-shinylive in Quarto against the same version of shinylive as is used by py-shinylive. To do this, we needed to move the quarto integration test to happen immediately after installing the r-shinylive package, to ensure that we get the released shinylive assets. Later, we'll build and install the latest shinylive, which may have the same version number as the last release (but will be different).
3. Finally, we also test r/py-shinylive together in Quarto using the latest, custom built shinylive.

ci(integration): Coordinate tested assets versions

---

README.md

It can be confusing (does the app need to use renv?) and it's an internal implementation detail that isn't broadly useful for users to know.
Fixes #84

docs: Remove {renv} from package discovery section

---

R/export.R

fix: URL for running static server needs to escape characters on Windows

---

R/assets.R

And use `message()` instead of `cat()` to make it easier to suppress the printed output.
``` r
info <- assets_info()
#> shinylive R package version:  0.1.1.9000
#> shinylive web assets version: 0.4.1.9000
#> 
#> Local cached shinylive asset dir:
#>     /Users/garrick/Library/Caches/shinylive
#> 
#> Installed assets:
#>     /Users/garrick/Library/Caches/shinylive/shinylive-0.4.1.9000
#>     /Users/garrick/Library/Caches/shinylive/shinylive-0.4.0
#>     /Users/garrick/Library/Caches/shinylive/shinylive-0.3.0
#>     /Users/garrick/Library/Caches/shinylive/shinylive-0.2.8
#>     /Users/garrick/Library/Caches/shinylive/shinylive-0.2.7
#>     /Users/garrick/Library/Caches/shinylive/shinylive-0.2.5
#>     /Users/garrick/Library/Caches/shinylive/shinylive-0.2.4
#> …
```

feat(assets_info): Return assets versions as invisible table

---

DESCRIPTION
NEWS.md
R/app_json.R
R/assets.R
R/cli.R
R/deps.R
R/export.R
R/packages.R
R/quarto_ext.R
R/utils.R
man/assets.Rd
man/export.Rd
tests/testthat/test-export.R

* Use cli for command line printing
* cli functions are called through wrappers that respect the `shinylive.quiet` global option and no-op if `quiet = TRUE`.
* `export(verbose=)` is deprecated in favor of `quiet`
* `assets_info()` gains a `quiet` argument
* Overly verbose file-copying messages are now suppressed in `export()`.

feat: Use {cli} for console printing

---

R/packages.R

For a previous version of webR, we required the full R version to be included as part of r-wasm repo URLs for Emscripten ABI compatability reasons. This was a temporary measure and is no longer required for the latest release of webR.
This PR restores the original short R versioning in repo.r-wasm.org URLs, matching the base R and r-universe behaviour.
The TODO mentioned combining two functions (one for r-wasm, the other for r-universe) but I've decided not to in case we diverge again in the future. Instead, I've just abstracted out the logic for showing a warning message when native and Wasm package versions don't match.
Fixes #110.

Restore short R version in r-wasm repo URLs

---

R/packages.R

Fixes error in shiny website build: 
```
Error in `lapply(text, glue_cmd, .envir = .envir)`:
! Could not evaluate cli `{}` expression: `pkg`.
Caused by error in `eval(expr, envir = envir)`:
! object 'pkg' not found
```
```
...
9. shinylive:::get_wasm_assets(desc, repo = "http://repo.r-wasm.org/")
10. shinylive:::check_repo_pkg_version(desc, ver)
11. cli::cli_warn(c("Package version mismatch for {.pkg {pkg}}, ensure the ver…
...
```

fix: Missing `pkg` variable

---

R/export.R
R/packages.R
R/quarto_ext.R
man/export.Rd
tests/testthat/apps/app-utf8/app.R
tests/testthat/test-export.R

Add maximum file size for bundling wasm assets

---

NEWS.md
R/packages.R

Packages listed under `LinkingTo` are required for _building_ dependent packages, but not loading them at runtime.
So, we can ignore these R packages when we're looking for dependencies to bundle with a webR+shinylive app. In webR 0.4.1, these packages will also be ignored when invoking `webr::install()`, and I'm told the native `install.packages()` already does the same.
See https://github.com/quarto-ext/shinylive/issues/59 for discussion.
c.f. https://github.com/r-wasm/webr/pull/463

Avoid `LinkingTo` dependencies in package resolution

---

NEWS.md
R/export.R
R/packages.R
R/quarto_ext.R
man/export.Rd
tests/testthat/test-export.R

Continuing the work in https://github.com/posit-dev/r-shinylive/pull/114 and earlier PRs, adds an environment variable `SHINYLIVE_WASM_PACKAGES`, defaulting to `TRUE`.
When `SHINYLIVE_WASM_PACKAGES` is set to `FALSE` or `0`, no wasm R packages are exported at all. This allows the user to turn off the mechanism when using Shinylive with Quarto, should they want to.
Closes https://github.com/quarto-ext/shinylive/issues/60.

Add `SHINYLIVE_WASM_PACKAGES` environment variable

---

NEWS.md
R/quarto_ext.R

This PR updates `build_app_resources()` so that it can create files in subdirectories, e.g.
```
data <- read.csv("data.csv")
```
This would previously fail because `writeLines()` would write to `"{appdir}/R/load_data.R"` but `{appdir}/R` doesn't exist yet.
While here I also added a check, after normalizing `file$name`, to make sure that file names are specified relative to the app directory and don't escape upwards.

Fix: Allow `shinylive-r` chunks to create files in subdirectories

---

NEWS.md
R/version.R

https://github.com/posit-dev/shinylive/releases/tag/v0.6.0
I'm thinking we should have the dev version of shinylive track the latest shinylive released assets version.
I've added a NEWS item so that it's clear we've updated the default, but that version number might change before a CRAN release, depending on when that happens next.

Update shinylive assets version

---

NEWS.md
R/quarto_ext.R

Avoids downloading the same R package(s) many times when using the shinylive extension in a Quarto project with multiple documents in subdirectories.
Fixes https://github.com/quarto-ext/shinylive/issues/61.
A fallback of `"."` (corresponding to the current behaviour) is set incase the `QUARTO_PROJECT_DIR` environment variable is ever unset.

feat: Build resources relative to Quarto project root

---

.github/workflows/R-CMD-check.yaml
R/export.R
R/packages.R
R/quarto_ext.R
R/version.R

This PR contains three changes to improve the bundling of static assets for loading R package binaries into webR.
1. Switch to using `.tgz` formatted R package binaries, support for which is introduced in webR 0.4.2 (https://github.com/r-wasm/webr/pull/477). This additionally fixes bundling R-Universe packages as static assets, as it now also serves packages in this new format.
2. When downloading package libraries served via GitHub Assets, allow for compressed libraries with filename `library.data.gz`.
3. For R packages hosted by the Bioconductor repository, grab the equivalent package from R-Universe's mirror. Due to 1, this fixes exporting Shinylive apps that use bioconductor packages.
This relies on using webR v0.4.2, and so requires a new version of the Shinylive assets. So, I will …

Improve Wasm R package binary assets downloading when exporting a Shinylive app

---

NEWS.md
R/version.R

Includes update to webR v0.5.5, which has support for [curl](https://jeroen.github.io/notes/webassembly-curl/).

Update shinylive assets to v0.10.5
